name: kubebox8 image job

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # force old Docker v2 Schema 2 manifest
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: kubebox8
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set build number
      id: build-number
      run: |
        BUILD_NUMBER=$(printf "%03d" ${{ github.run_number }})
        echo "BUILD_NUMBER=${BUILD_NUMBER}" >> $GITHUB_ENV
        echo "build-number=${BUILD_NUMBER}" >> $GITHUB_OUTPUT

    - name: Version info
      run: |
        docker version
        echo
        make --version
        echo

    - name: Build Docker image
      run: |
        make build DOCKER_REGISTRY=${{ env.REGISTRY }} BUILD_NUMBER=${{ env.BUILD_NUMBER }}

    - name: Push Docker image
      if: github.event_name != 'pull_request'
      run: |
        make push DOCKER_REGISTRY=${{ env.REGISTRY }} BUILD_NUMBER=${{ env.BUILD_NUMBER }}
